TRAIN:
  DATASET: 'breakfast'
  BATCH_SIZE: 1
  CHECKPOINT_PERIOD: 2
  AUTO_RESUME: False
DATA:
  CV_SPLIT_NUM: 1
  BACKGROUND_INDICES: [0]
SOLVER:
  BASE_LR: 0.00025
  MAX_EPOCH: 150
  WEIGHT_DECAY: 10e-4
  OPTIMIZING_METHOD: 'adam'
  LR_POLICY: 'constant_cosine_decay'
  WARMUP_EPOCHS: 15
  T_MAX: 180
MODEL:
  NAME: 'ltc'
  LOSS_FUNC: 'ce_mse'
  MSE_LOSS_FRACTION: 0.17
  NUM_CLASSES: 48
  INPUT_DIM: 2048
  LTC:
    NUM_LAYERS: 9
    NUM_STAGES: 4
    MODEL_DIM: 64
    WINDOWED_ATTN_W: 64
    LONG_TERM_ATTN_G: 8
    CHANNEL_MASKING_PROB: 0.3
DATA_LOADER:
  NUM_WORKERS: 2
  PIN_MEMORY: True
NUM_GPUS: 1
RNG_SEED: 115
LOG_PERIOD: 100
OUTPUT_DIR: ./experiments/breakfast